# Generated by Django 4.2.28 on 2026-02-14 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_draftlocation_parent_uri'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draftlocation',
            name='project',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
