# Generated by Django 4.2.28 on 2026-02-14 17:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_remove_draftlocation_project_delete_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonsCategoryImageCountCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, unique=True)),
                ('image_count', models.PositiveIntegerField(default=0)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='ViewItImageCountCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wikidata_qid', models.CharField(max_length=32, unique=True)),
                ('image_count', models.PositiveIntegerField(default=0)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['wikidata_qid'],
            },
        ),
    ]
